"""
File attachments.

The `photo`, `voice` and `document` message kinds existed from the first version
and there was never anywhere to put a file, so none of them could actually be
used. This is that missing half.

Files live on disk rather than in SQLite. Storing megabytes of image data in the
database would bloat every backup and push large blobs through the same write
lock that ordinary messages contend for.

Four rules are doing real security work here, and none of them are optional:

  The filename from the client never touches the filesystem.
      A name like "../../../etc/passwd" would escape the upload directory. The
      file on disk is named after a generated id; the original name is kept as
      metadata for display only.

  The size limit is enforced while reading, not after.
      Checking Content-Length trusts the client, and reading the whole body
      first to measure it means a large upload has already been buffered.

  HTML and SVG are refused.
      Both can carry script. Served from our own origin they would run with our
      cookies and tokens, which turns an upload box into stored XSS.

  Downloads are authorised against the chat the file was sent to.
      A random id is not an access control. Anyone who can guess or is given an
      id would otherwise be able to read a private attachment.
"""

import asyncio
import os
import shutil
import time
import uuid

import db

# Where the files go. Kept beside the database so one mounted disk covers both.
UPLOAD_DIR = os.path.join(db.DATA_DIR, "uploads")

MAX_UPLOAD_BYTES = int(os.environ.get("MAX_UPLOAD_BYTES", 256 * 1024 * 1024))  # 256 MB

# Read in chunks so memory use does not scale with the size of the upload.
CHUNK_BYTES = 64 * 1024

# What may be inlined in a page. Anything not listed is still accepted, but is
# served as a download rather than rendered.
INLINE_TYPES = {
    "image/jpeg", "image/png", "image/gif", "image/webp",
    "audio/mpeg", "audio/ogg", "audio/wav", "audio/webm", "audio/mp4",
    "video/mp4", "video/webm",
    "application/pdf",
}

# Refused outright. These execute script when served from our own origin.
BLOCKED_TYPES = {
    "text/html", "application/xhtml+xml",
    "image/svg+xml", "application/xml", "text/xml",
    "application/javascript", "text/javascript",
}


class UploadTooLarge(Exception):
    pass


class UploadTypeRefused(Exception):
    pass


def ensure_directory():
    os.makedirs(UPLOAD_DIR, exist_ok=True)


def path_for(attachment_id: str) -> str:
    """
    Where an attachment lives on disk.

    The id is generated by us and is hex plus a fixed prefix, so it cannot
    contain a separator or a parent-directory reference.
    """
    return os.path.join(UPLOAD_DIR, attachment_id)


async def store(upload, uploader_id: str) -> dict:
    """
    Write an uploaded file to disk and record it.

    `upload` is a Starlette UploadFile. Returns the attachment row.
    """
    content_type = (upload.content_type or "application/octet-stream").split(";")[0].strip().lower()
    if content_type in BLOCKED_TYPES:
        raise UploadTypeRefused(f"{content_type} files are not accepted")

    ensure_directory()
    attachment_id = f"att_{uuid.uuid4().hex}"
    destination = path_for(attachment_id)

    written = 0
    # `store()` is `async def` and runs directly on the event loop (it's
    # awaited from request handlers, not dispatched to a thread pool the way
    # a sync `def` route is), so a plain blocking open()/write() here would
    # freeze every other request and websocket message for as long as each
    # disk write takes — for a large upload that's up to MAX_UPLOAD_BYTES /
    # CHUNK_BYTES (~390 for a 25MB file) blocking syscalls in a row, all on
    # the one thread the whole app's async I/O shares. asyncio.to_thread
    # moves each write off the loop; upload.read() is already non-blocking.
    target = await asyncio.to_thread(open, destination, "wb")
    try:
        while True:
            chunk = await upload.read(CHUNK_BYTES)
            if not chunk:
                break

            written += len(chunk)
            if written > MAX_UPLOAD_BYTES:
                # Stop as soon as the limit is passed rather than finishing
                # the write and rejecting afterwards.
                raise UploadTooLarge(
                    f"Files must be under {MAX_UPLOAD_BYTES // (1024 * 1024)} MB")

            await asyncio.to_thread(target.write, chunk)
    except BaseException:
        # BaseException, not Exception: a request cancelled mid-upload (the
        # client disconnected while a chunk write was in flight on another
        # thread) raises asyncio.CancelledError, which does NOT subclass
        # Exception — an `except Exception` here would let a cancelled
        # upload skip this cleanup entirely and leave a partial file with no
        # attachment row pointing at it.
        await asyncio.to_thread(target.close)
        if os.path.exists(destination):
            os.remove(destination)
        raise
    else:
        await asyncio.to_thread(target.close)

    if written == 0:
        os.remove(destination)
        raise UploadTypeRefused("The file is empty")

    db.execute(
        """
        INSERT INTO attachments (id, uploader_id, message_id, story_id, avatar_of_user_id,
                                 file_name, content_type, size_bytes, created_at)
        VALUES (?, ?, NULL, NULL, NULL, ?, ?, ?, ?)
        """,
        (attachment_id, uploader_id, safe_display_name(upload.filename),
         content_type, written, time.time()),
    )

    return dict(db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,)))


def safe_display_name(name: str | None) -> str:
    """
    Reduce a client-supplied filename to something safe to show and to echo in a
    download header. Only the final component is kept, and separators are
    stripped, so nothing that reaches storage or a header can be a path.
    """
    if not name:
        return "file"
    cleaned = os.path.basename(name).replace("\\", "").replace("/", "").replace('"', "")
    cleaned = "".join(character for character in cleaned if character.isprintable())
    return cleaned.strip()[:120] or "file"


def attach_to_message(attachment_id: str, message_id: str, uploader_id: str) -> dict | None:
    """
    Bind an upload to the message that carries it.

    Only the person who uploaded it may attach it, and only once — otherwise
    someone could take another user's attachment id and re-send their file, or
    move a file from a chat they left into one they can still read.
    """
    changed = db.execute(
        """
        UPDATE attachments SET message_id = ?
        WHERE id = ? AND uploader_id = ? AND message_id IS NULL
        """,
        (message_id, attachment_id, uploader_id),
    )
    if changed.rowcount == 0:
        return None
    return dict(db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,)))


def attach_to_story(attachment_id: str, story_id: str, uploader_id: str) -> dict | None:
    """Same rule as attach_to_message, for a status/story instead of a chat message."""
    changed = db.execute(
        """
        UPDATE attachments SET story_id = ?
        WHERE id = ? AND uploader_id = ? AND message_id IS NULL AND story_id IS NULL
        """,
        (story_id, attachment_id, uploader_id),
    )
    if changed.rowcount == 0:
        return None
    return dict(db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,)))


def attach_to_avatar(attachment_id: str, user_id: str) -> dict | None:
    """
    Bind an upload as a profile photo. `user_id` doubles as both the owner
    of the new avatar and the required uploader — you can only ever set
    YOUR OWN account's photo from YOUR OWN upload, never someone else's.
    """
    changed = db.execute(
        """
        UPDATE attachments SET avatar_of_user_id = ?
        WHERE id = ? AND uploader_id = ? AND message_id IS NULL AND story_id IS NULL
          AND avatar_of_user_id IS NULL
        """,
        (user_id, attachment_id, user_id),
    )
    if changed.rowcount == 0:
        return None
    return dict(db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,)))


def attach_to_cover(attachment_id: str, user_id: str) -> dict | None:
    """Bind an upload as a user's cover/banner photo — the cover counterpart to
    attach_to_avatar; you can only set YOUR OWN cover from YOUR OWN upload."""
    changed = db.execute(
        """
        UPDATE attachments SET cover_of_user_id = ?
        WHERE id = ? AND uploader_id = ? AND message_id IS NULL AND story_id IS NULL
          AND avatar_of_user_id IS NULL AND avatar_of_chat_id IS NULL AND cover_of_user_id IS NULL
        """,
        (user_id, attachment_id, user_id),
    )
    if changed.rowcount == 0:
        return None
    return dict(db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,)))


def attach_to_chat_avatar(attachment_id: str, chat_id: str, uploader_id: str) -> dict | None:
    """
    Bind an upload as a chat's (group/channel/community) photo — the chat
    counterpart to attach_to_avatar. The caller (main.py) has already checked
    the uploader is an admin of the chat; here we only enforce that the upload
    is theirs and still unbound, so it can't be stolen from another purpose.
    """
    changed = db.execute(
        """
        UPDATE attachments SET avatar_of_chat_id = ?
        WHERE id = ? AND uploader_id = ? AND message_id IS NULL AND story_id IS NULL
          AND avatar_of_user_id IS NULL AND avatar_of_chat_id IS NULL
        """,
        (chat_id, attachment_id, uploader_id),
    )
    if changed.rowcount == 0:
        return None
    return dict(db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,)))


def attach_to_product(attachment_id: str, product_id: str, uploader_id: str) -> dict | None:
    """Bind an upload as a product's photo — the product counterpart to
    attach_to_avatar/attach_to_chat_avatar. Caller has already checked the
    product belongs to this uploader; here we only enforce the upload is
    theirs and still unbound."""
    changed = db.execute(
        """
        UPDATE attachments SET product_of_id = ?
        WHERE id = ? AND uploader_id = ? AND message_id IS NULL AND story_id IS NULL
          AND avatar_of_user_id IS NULL AND avatar_of_chat_id IS NULL
          AND cover_of_user_id IS NULL AND product_of_id IS NULL
        """,
        (product_id, attachment_id, uploader_id),
    )
    if changed.rowcount == 0:
        return None
    return dict(db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,)))


def duplicate_for_message(attachment_id: str, new_message_id: str) -> str | None:
    """
    Copy an attachment's file to a new id, bound directly to a different
    message.

    Used for broadcast fan-out: one uploaded file becomes many independent
    messages (one per recipient's DM), and message_id is a single-owner
    binding — the same rule that keeps a normal upload-then-send from being
    re-attached to a second message means one attachment row can't serve two
    messages either. Copying is cheap relative to correctness here: a stray
    half-shared attachment row would be a real authorization hazard (see
    download_file's per-message chat check in main.py).
    """
    source = db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,))
    if source is None:
        return None

    new_attachment_id = f"att_{uuid.uuid4().hex}"
    shutil.copyfile(path_for(attachment_id), path_for(new_attachment_id))

    db.execute(
        """
        INSERT INTO attachments (id, uploader_id, message_id, story_id, file_name,
                                 content_type, size_bytes, created_at)
        VALUES (?, ?, ?, NULL, ?, ?, ?, ?)
        """,
        (new_attachment_id, source["uploader_id"], new_message_id, source["file_name"],
         source["content_type"], source["size_bytes"], time.time()),
    )
    return new_attachment_id


def describe(attachment_id: str) -> dict | None:
    """The metadata a client needs to render an attachment, without the file."""
    row = db.query_one("SELECT * FROM attachments WHERE id = ?", (attachment_id,))
    if row is None:
        return None
    attachment = dict(row)
    return {
        "attachment_id": attachment["id"],
        "file_name": attachment["file_name"],
        "content_type": attachment["content_type"],
        "size_bytes": attachment["size_bytes"],
        "inline": attachment["content_type"] in INLINE_TYPES,
    }


def delete(attachment_id: str):
    """Remove an attachment and its file."""
    destination = path_for(attachment_id)
    if os.path.exists(destination):
        os.remove(destination)
    db.execute("DELETE FROM attachments WHERE id = ?", (attachment_id,))


def sweep_orphans(older_than_seconds: float = 3600) -> int:
    """
    Delete uploads that were never sent.

    Opening the file picker and then changing your mind leaves a file on disk
    with no message pointing at it. Without this they accumulate forever.
    """
    cutoff = time.time() - older_than_seconds
    orphans = db.query_all(
        "SELECT id FROM attachments WHERE message_id IS NULL AND story_id IS NULL "
        "AND avatar_of_user_id IS NULL AND avatar_of_chat_id IS NULL "
        "AND cover_of_user_id IS NULL AND product_of_id IS NULL AND created_at < ?",
        (cutoff,),
    )
    for orphan in orphans:
        delete(orphan["id"])
    return len(orphans)
